//dados de tipos de café
const tiposDeCafe = [
  {
    id: 1,
    image:
      "https://cdn.awsli.com.br/2500x2500/18/18885/produto/59953405/896e7bcf46.jpg",
    tipo: "Arábica",
    sabor: "suave, acidez equilibrada, aroma intenso",
    caracteristicas: "considerado o café nobre, diversas variedades",
    origem: "Brasil, Colômbia",
    torraIdeal: "média",
    metodosPreparo: "coado, espresso",
    notasDeDegustacao: "chocolate, frutas cítricas",
    link: "https://pt.wikipedia.org/wiki/Coffea_arabica",
  },
  {
    id: 2,
    image:
      "https://portalagromais.com.br/wp-content/uploads/2024/09/Coffee-fruits.jpg",
    tipo: "Robusta",
    sabor: "forte, corpo intenso, baixo teor de acidez",
    caracteristicas: "mais resistente a pragas, sabor mais encorpado",
    origem: "Vietnã, Indonésia",
    torraIdeal: "escura",
    metodosPreparo: "espresso café com leite",
    notasDeDegustacao: "terroso, nozes",
    link: "https://pt.wikipedia.org/wiki/Coffea_canephora",
  },
  {
    id: 3,
    image: "https://ufes.br/sites/default/files/field/image/conilon_1.jpg",
    tipo: "Conilon",
    sabor: "forte, amargo, corpo intenso",
    caracteristicas: "mais resistente, amplamente cultivado no Brasil",
    origem: "Brasil",
    torraIdeal: "escura",
    metodosPreparo: "espresso café com leite",
    notasDeDegustacao: "terroso, vegetal",
    link: "https://pt.wikipedia.org/wiki/Coffea_canephora",
  },
  {
    id: 4,
    image:
      "https://cdn.awsli.com.br/2548/2548474/arquivos/cafe-bourbon-1024x768.jpg",
    tipo: "Bourbon",
    sabor: "suave, acidez equilibrada, aroma floral",
    caracteristicas: "variedade do arábica, grãos grandes e arredondados",
    origem: "Brasil",
    torraIdeal: "média",
    metodosPreparo: "coado espresso",
    notasDeDegustacao: "frutas vermelhas, caramelo",
    link: "https://en.wikipedia.org/wiki/Bourbon_coffee#:~:text=Bourbon%20is%20a%20cultivar%20of,Both%20originated%20in%20Yemen.&text=Bourbon%20coffee%20was%20first%20produced,as%20Île%20Bourbon%20before%201789.",
  },
  {
    id: 5,
    image:
      "https://reidocafe.com.br/wp-content/uploads/2023/04/cafe-Catuai.jpg",
    tipo: "Catuaí",
    sabor: "suave, acidez equilibrada, corpo médio",
    caracteristicas: "variedade do arábica, alta produtividade",
    origem: "Brasil",
    torraIdeal: "média",
    metodosPreparo: "coado espresso",
    notasDeDegustacao: "chocolate, frutas cítricas",
    link: "https://pt.wikipedia.org/wiki/Coffea_arabica",
  },
  {
    id: 6,
    image:
      "https://uniquecafes.com.br/wp-content/uploads/2021/05/01-Cafe-Mundo-Novo.jpg",
    tipo: "Novo Mundo",
    sabor: "suave, corpo médio, aroma floral",
    caracteristicas: "variedade do arábica, resistente a doenças",
    origem: "Brasil",
    torraIdeal: "média",
    metodosPreparo: "coado espresso",
    notasDeDegustacao: "frutas cítricas, caramelo",
    link: "https://pt.wikipedia.org/wiki/Café#:~:text=Na%20sua%20peregrinação%20pelo%20mundo,Porto%20Rico%20e%20Cuba.%20Gabriel",
  },
  {
    id: 7,
    image:
      "https://static.wixstatic.com/media/99ce46_7162fa619f6444acb0f17994c29d25fb~mv2.jpg/v1/fill/w_715,h_562,al_c,q_85,enc_auto/99ce46_7162fa619f6444acb0f17994c29d25fb~mv2.jpg",
    tipo: "Caturra",
    sabor: "suave, acidez equilibrada, corpo médio",
    caracteristicas: "variedade do bourbon, planta de porte menor",
    origem: "Brasil",
    torraIdeal: "média",
    metodosPreparo: "coado espresso",
    notasDeDegustacao: "avelã, chocolate",
    link: "https://pt.wikipedia.org/wiki/Coffea_arabica",
  },
  {
    id: 8,
    image: "https://reidocafe.com.br/wp-content/uploads/2023/03/cafe-acaia.jpg",
    tipo: "Acaiá",
    sabor: "suave, acidez equilibrada, corpo médio",
    caracteristicas: "variedade do arábica, grãos grandes",
    origem: "Brasil",
    torraIdeal: "média",
    metodosPreparo: "coado espresso",
    notasDeDegustacao: "frutas vermelhas, caramelo",
    link: "https://pt.wikipedia.org/wiki/Coffea_arabica",
  },
];

export default tiposDeCafe;
